// apps/next-showcase-app/src/pages/index.tsx
import { Restaurant, RestaurantsReponse } from "../types/restaurants";
import FiltersSection from "../components/filters";
import StoreTile from "../components/store";
import { GetServerSideProps } from "next";
import queryStringModule from "querystring";
import Head from "next/head";

export default function Home({
  restaurantsList,
  queryString,
}: {
  restaurantsList: Restaurant[];
  queryString: string;
}) {
  return (
    <>
      <Head>
        <link rel="apple-touch-icon" href="icon.png" />
        <meta name="theme-color" content="#fafafa" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="apple-touch-icon" href="icon.png" />
      </Head>
      <section className="content">
        <h2>Stores list{queryString}</h2>
        <FiltersSection />
        <section className="stores" id="stores-list">
          {restaurantsList.map((restaurant, index) => (
            <StoreTile index={index} restaurant={restaurant} key={index} />
          ))}
        </section>
      </section>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{
  restaurantsList: Restaurant[];
  queryString: string;
}> = async ({ query }) => {
  const queryString = queryStringModule.stringify(query);
  const restaurantsUrl = `https://comida.sillyapps.io/restaurants.json?${queryString}`;
  const countriesUrl = `https://comida.sillyapps.io/countries.json?${queryString}`;
  const citiesUrl = `https://comida.sillyapps.io/cities.json?${queryString}`;

  const [res] = await Promise.all([
    fetch(restaurantsUrl),
    fetch(countriesUrl),
    fetch(citiesUrl),
  ]);

  const restaurants: RestaurantsReponse = await res.json();

  const restaurantsList = restaurants.elements.filter(
    ({ type, singleData }: Restaurant) =>
      type === "SINGLE" && singleData?.type === "STORE" && singleData?.storeData
  );

  return { props: { restaurantsList, queryString } };
};

// apps/nuxt-showcase-app/pages/index.vue
<template>
  <h2>Stores list</h2>
  <AppFilters/>
  <section class="stores" id="stores-list">
    <store-tile v-for="restaurant in restaurantsList" :restaurant="restaurant"/>
  </section>

</template>
<script setup lang="ts">
import AppFilters from "~/components/AppFilters.vue";
import StoreTile from "~/components/StoreTile.vue";
import {RestaurantesReponse} from "~/types/RestaurantesResponse";

const {data, pending, error, refresh} = await useAsyncData(
    'restaurants',
    () => Promise.all(
        [
          $fetch('https://comida.sillyapps.io/restaurants.json'),
          $fetch('https://comida.sillyapps.io/countries.json'),
          $fetch('https://comida.sillyapps.io/cities.json'),
        ]
    ).then(responses => responses[0])
)

const restaurantsList = ((unref(data)) as RestaurantesReponse).elements.filter(
    element => {
      if (element.type !== 'SINGLE') return false;
      if (element.singleData?.type !== 'STORE') return false;
      if (!element.singleData?.storeData) return false;
      return true
    }
)


</script>
