// apps/next-showcase-app/src/app/event-loop/page.tsx
"use client";

import blockEventLoop from  '../../../blockEventLoop'
import { useRouter } from 'next/navigation';
export default function EventLoop() {
  const router = useRouter()
  const handleClick = () => {
    blockEventLoop();
    router.push('/')
  };
  return (
    <>
      <h1>Performance test</h1>
      <button onClick={handleClick}>Block Event Loop</button>
    </>
  );
}

// apps/nuxt-showcase-app/pages/event-loop/index.vue
<script setup lang="ts">
import blockEventLoop from '../../blockEventLoop'
const router = useRouter();
function handleClick() {
  blockEventLoop();
  router.push("/");
}
</script>
<template>
  <div>
    <h1>Performance test</h1>
    <button @click="handleClick">Block Event Loop</button>
  </div>
</template>
